name: CI Pipeline

# Run on PR or push into develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Setup repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          chmod +x ./ci/*
          ./ci/install.sh

          
      # Step 3: Build binaries
      - name: Build binaries
        run: |
          # mkdir -p ci/
          chmod +xw ./ci/*
          ./ci/build.sh
          
      # Step 4: Run tests
      #- name: Run tests
      #  run: |
      #    ./run_tests.sh # TBD
          
      # Step 5: Upload artifacts
      - name: List files in build directory
        run: ls -al ./ci/build

      - name: Upload binaries and test reports
        uses: actions/upload-artifact@v3
        with:
          name: binaries-and-reports
          path: |
            ./ci/build/**

